name = "Networks"
uuid = "634dcf3f-6aa7-47ba-9e85-1fb329c9ebfe"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez+git@bsc.es>"]
version = "0.1.1"

[deps]
ValSplit = "0625e100-946b-11ec-09cd-6328dd093154"

[compat]
ValSplit = "0.1.1"
